server:
  port: 8080

spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false